#!/usr/bin/env python3
"""
Render HTML ad files to PNG images using Playwright.

Takes HTML ad files generated by the /html-ad skill and renders them to
print-ready PNG files at exact Meta ad dimensions (1080×1080 and 1080×1350).

Usage:
    python render-ads.py --input campaigns/{name}/images/html/ \
                         --output campaigns/{name}/images/ \
                         --width 1080 --height 1080

    python render-ads.py --input campaigns/{name}/images/html/ \
                         --output campaigns/{name}/images/ \
                         --sizes 1:1 4:5

Output:
    {ad-name}.png          (1080×1080 — square feed)
    {ad-name}_4x5.png      (1080×1350 — portrait feed)

Requirements:
    pip install playwright
    playwright install chromium
"""

import argparse
import json
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render HTML ad files to PNG using Playwright"
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Directory containing HTML ad files",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Directory to write PNG files to",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=1080,
        help="Viewport width in pixels (default: 1080)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=1080,
        help="Viewport height in pixels (default: 1080)",
    )
    parser.add_argument(
        "--sizes",
        nargs="+",
        default=["1:1", "4:5"],
        choices=["1:1", "4:5", "9:16"],
        help="Aspect ratios to render (default: 1:1 4:5)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )
    return parser.parse_args()


def get_dimensions(ratio: str, base_width: int = 1080) -> tuple[int, int]:
    """Return (width, height) for a given aspect ratio at base_width."""
    ratios = {
        "1:1": (base_width, base_width),
        "4:5": (base_width, int(base_width * 5 / 4)),
        "9:16": (base_width, int(base_width * 16 / 9)),
    }
    return ratios[ratio]


def get_suffix(ratio: str) -> str:
    """Return filename suffix for a given aspect ratio."""
    suffixes = {
        "1:1": "",
        "4:5": "_4x5",
        "9:16": "_9x16",
    }
    return suffixes[ratio]


def render_html_files(
    input_dir: Path,
    output_dir: Path,
    sizes: list[str],
    base_width: int = 1080,
) -> list[dict]:
    """Render all HTML files in input_dir to PNG files in output_dir."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "Error: Playwright not installed.\n"
            "Run: pip install playwright && playwright install chromium",
            file=sys.stderr,
        )
        sys.exit(1)

    html_files = sorted(input_dir.glob("*.html"))
    if not html_files:
        print(f"No HTML files found in {input_dir}", file=sys.stderr)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)
    results = []

    with sync_playwright() as p:
        browser = p.chromium.launch()

        for html_file in html_files:
            stem = html_file.stem
            file_results = {"name": stem, "outputs": []}

            for ratio in sizes:
                width, height = get_dimensions(ratio, base_width)
                suffix = get_suffix(ratio)
                output_path = output_dir / f"{stem}{suffix}.png"

                page = browser.new_page(viewport={"width": width, "height": height})
                page.goto(f"file://{html_file.resolve()}")
                page.wait_for_load_state("networkidle")
                page.screenshot(path=str(output_path), clip={
                    "x": 0, "y": 0, "width": width, "height": height
                })
                page.close()

                file_results["outputs"].append({
                    "ratio": ratio,
                    "dimensions": f"{width}×{height}",
                    "path": str(output_path),
                })

                print(f"  ✓ {output_path.name} ({width}×{height})")

            results.append(file_results)

        browser.close()

    return results


def main() -> None:
    args = parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)

    if not input_dir.exists():
        print(f"Error: Input directory not found: {input_dir}", file=sys.stderr)
        sys.exit(1)

    if not args.json:
        print(f"Rendering HTML ads → PNG")
        print(f"  Input:  {input_dir}")
        print(f"  Output: {output_dir}")
        print(f"  Sizes:  {', '.join(args.sizes)}")
        print()

    results = render_html_files(input_dir, output_dir, args.sizes, args.width)

    total = sum(len(r["outputs"]) for r in results)

    if args.json:
        print(json.dumps({"files_rendered": len(results), "pngs_created": total, "results": results}, indent=2))
    else:
        print()
        print(f"Done. {len(results)} HTML files → {total} PNG files saved to {output_dir}")


if __name__ == "__main__":
    main()
